- hosts: balancer
  become: yes
  tasks: 
  - name: Garantindo HAProxy
    package:
      name: haproxy
      state: present
  - name: Garantindo configuracao
    copy:
      src: /root/playbooks/files/haproxy.cfg
      dest: /etc/haproxy
    register: config
  - debug:
      msg: '{{ config }}'
  - name: Recarregando servico HAProxy
    service: #systemd
      name: haproxy
      state: restarted # stopped, restarted, reloaded
    when: config.changed == True
  - name: Garantindo servico HAProxy
    service: #systemd
      name: haproxy
      state: started # stopped, restarted, reloaded
      enabled: yes
