- hosts: docker
  become: yes
  vars:
    user: lighttpd
    group: lighttpd
  tasks: 
  - name: Verificando distribuicao
    set_fact:
      user: www-data
      group: www-data
    when: ansible_distribution|lower == 'debian'
  - name: Garantindo o epel-release em CentOS
    package:
      name: epel-release
      state: present
    when: ansible_distribution|lower == 'centos'
  - name: Garantindo Lighttpd e Git
    package:
      name: ['lighttpd', 'git']
      state: present
  - name: Garantindo configuracoes
    template:
      src: '{{item}}'
      dest: /etc/lighttpd
      owner: root
      group: root
    loop: 
    - /root/playbooks/files/mime-types.conf
    - /root/playbooks/files/lighttpd.conf
    register: config
  - name: Garantindo configuracoes de proxy
    blockinfile:
      path: /etc/lighttpd/proxy.conf
      create: yes
      block: |
        $SERVER["socket"] == ":8080" {
            proxy.server = ( "" => ( ( "host" => "192.168.10.10", "port" => "80" )))
        }
      insertafter: '#Configuracoes do Ansible' 
    register: proxy
  - name: Garantindo diretorios
    file:
      path: '{{ item }}'
      owner: '{{ user }}'
      group: '{{ group }}'
      state: directory 
    loop:
    - /srv/www/html
    - /var/cache/lighttpd
    - /var/logs/lighttpd
  - name: Reiniciando Lighttpd para configuracoes
    service:
      name: lighttpd
      state: restarted
    when: config.changed or proxy.changed
  - name: Garantindo servico do Lighttpd
    service: #systemd
      name: lighttpd
      state: started # stopped, restarted, reloaded
      enabled: yes
  - name: Removendo arquivos /srv/www/html
    shell: 'find /srv/www/html/ -delete -mindepth 1'
  - name: Garantindo site
    git:
      repo: http://172.27.11.10:3000/devops/site.git
      dest: /srv/www/html
      force: yes
  - name: Garantindo contexto /srv/www/html
    command: 'restorecon -R /srv/www/html'
    when: ansible_distribution|lower == 'centos'
  - get_url:
      url: http://172.27.11.10:3000/devops/site/raw/branch/ansible/index.html 
      dest: /srv/www/html/index.html
      force: yes
  - name: Testando conexao com o loadbalancer
    uri:
      url: http://172.27.11.20
      status_code: [200, 302, 304]
    register: response
    delegate_to: localhost
    run_once: yes
#  - name: Verificando status da conexao
#    fail: 
#      msg: '[{{ response.status }}] - Load balancer com problemas'
#    run_once: yes
#    when: response.status != 200
